name: notzz
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  go_router: ^14.2.0
  injectable: ^2.4.2
  uuid: ^4.4.0
  injectable_generator: ^2.6.1
  get_it: ^7.7.0
  kt_dart: ^1.1.0
  json_annotation: ^4.9.0
  flutter_quill: ^9.4.6
  flutter_hooks: ^0.20.5
  flutter_floating_bottom_bar: ^1.2.0
  iconsax: ^0.0.8
  dotted_dashed_line: ^0.0.3
  another_flushbar: ^1.12.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
